name: Continuous Deployment
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Deply Self
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          export NIX_PATH=nixpkgs=https://github.com/Fresheyeball/nixpkgs/archive/060d08cc74919d808cd3608e8391ab12c17cfeb2.tar.gz
          export NIXOPS_STATE=$GITHUB_WORKSPACE/nixops-state.nixops
          source cd-env.sh
          eval "$(ssh-agent -s)"
          ssh-add /build-key
          nixops destroy --all && nixops delete --all
          nixops create -d ardana-ci realm.nix
          nixops deploy -d ardana-ci
          nixops destroy --all && nixops delete --all

