name: Continuous Delivery
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: deploy self
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          export NIX_PATH=nixpkgs=https://github.com/Fresheyeball/nixpkgs/archive/ef75aabffb4edc75bf4639af8c454eea267fa253.tar.gz
          export NIXOPS_STATE=$GITHUB_WORKSPACE/nixops-state.nixops

          source dummy-env.sh
          eval "$(ssh-agent -s)"
          ssh-add /build-key
          mkdir -p ~/.ssh
          ssh-keyscan 138.68.57.54 > ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts
          echo $HOME ~/.ssh/known_hosts

          ssh root@138.68.57.54 -v

