name: Continuous Integration
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: nix check
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          source dummy-env.sh
          eval "$(ssh-agent -s)"
          ssh-add /build-key
          export NIX_PATH=nixpkgs=https://github.com/Fresheyeball/nixpkgs/archive/ef75aabffb4edc75bf4639af8c454eea267fa253.tar.gz
          which nixops; nixops --version
          nixops destroy --all && nixops delete --all
          export NAME="ardana-ci-$(date +%s%N)-$RANDOM"
          nixops create -d $NAME realm.nix
          nixops deploy -d $NAME --dry-run
          nixops destroy --all && nixops delete --all
