name: Continuous Integration
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Dry Run
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          export NIX_PATH=nixpkgs=https://github.com/nixinator/nixpkgs/archive/08965379be2dc0623aed11aa4b29c95636fc4f43.tar.gz
          export NIXOPS_STATE=$GITHUB_WORKSPACE/nixops-state.nixops
          source dummy-env.sh
          eval "$(ssh-agent -s)"
          ssh-add /build-key
          nixops destroy --all && nixops delete --all
          nixops create -d ardana-ci realm.nix
          nixops deploy -d ardana-ci --dry-run
          nixops destroy --all && nixops delete --all
